export default {
    LOG_IN: 'LOG_IN',
    CHANGE_LOGIN_STAGE: 'CHANGE_LOGIN_STATE',
    CHANGE_SIGN_UP_STATE: 'CHANGE_SIGN_UP_STATE',
    SEARCH: 'SEARCH',
    LOAD_USER_INFO: 'LOAD_USER_INFO',
    LOAD_FRIEND_INFO: 'LOAD_FRIEND_INFO',
}