export default {
    LOG_IN: 'LOG_IN',
    CHANGE_LOGIN_STAGE: 'CHANGE_LOGIN_STATE',
    CHANGE_SIGN_UP_STATE: 'CHANGE_SIGN_UP_STATE',
    LOAD_SEARCH_RESULT: 'LOAD_SEARCH_RESULT',
    LOAD_USER_INFO: 'LOAD_USER_INFO',
    LOAD_FRIEND_INFO: 'LOAD_FRIEND_INFO',
    CHANGE_CHATOBJ: 'CHANGE_CHATOBJ',
    CHANGE_CHATMESS: 'CHANGE_CHATMESS',
    MOVE_SCROLL: 'MOVE_SCROLL',
    CHANGE_SHOW_SETTING: 'CHANGE_SHOW_SETTING',
    CHANGE_SEARCH_MODE: 'CHANGE_SEARCH_MODE',
    VIEW_INFO: 'VIEW_INFO',
    UPDATE_FRIEND: 'UPDATE_FRIEND',
    LOAD_GROUPS_INFO: 'LOAD_GROUP_INFO',
    VIEW_GROUP: 'VIEW_GROUP',
    LOAD_ROOMS_INFO: 'LOAD_ROOMS_INFO',
    ADD_NEW_ROOM: 'ADD_NEW_ROOM'
}