export default {
    LOG_IN: 'LOG_IN',
    CHANGE_LOGIN_STAGE: 'CHANGE_LOGIN_STATE',
    CHANGE_SIGN_UP_STATE: 'CHANGE_SIGN_UP_STATE',
    LOAD_SEARCH_RESULT: 'LOAD_SEARCH_RESULT',
    LOAD_USER_INFO: 'LOAD_USER_INFO',
    LOAD_FRIEND_INFO: 'LOAD_FRIEND_INFO',
    CHANGE_CHATOBJ: 'CHANGE_CHATOBJ',
    CHANGE_CHATMESS: 'CHANGE_CHATMESS',
    MOVE_SCROLL: 'MOVE_SCROLL',
    CHANGE_SHOW_SETTING: 'CHANGE_SHOW_SETTING',
    CHANGE_SEARCH_MODE: 'CHANGE_SEARCH_MODE'
}